/*
 * This source file was generated by the Gradle 'init' task
 */
package com.chibikookie.arcanerig;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

import com.chibikookie.arcanerig.api.ArcaneRigApi;
import com.chibikookie.arcanerig.api.ArcaneRigService;
import com.chibikookie.arcanerig.api.SlotDescriptor;
import com.chibikookie.arcanerig.components.ArcaneRigData;
import com.chibikookie.arcanerig.components.ArcaneRigData.SlotEntry;
import com.chibikookie.arcanerig.interactions.RingInteraction;
import com.hypixel.hytale.component.ComponentType;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.server.core.entity.entities.Player;
import com.hypixel.hytale.server.core.event.events.player.PlayerReadyEvent;
import com.hypixel.hytale.server.core.inventory.ItemStack;
import com.hypixel.hytale.server.core.modules.interaction.interaction.config.Interaction;
import com.hypixel.hytale.server.core.plugin.JavaPlugin;
import com.hypixel.hytale.server.core.plugin.JavaPluginInit;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;

public class ArcaneRigPlugin extends JavaPlugin {
    private static ArcaneRigPlugin instance;
    private static volatile ArcaneRigApi API;
    private final ArcaneRigService service;
    private ComponentType<EntityStore, ArcaneRigData> arcaneRigDataComponentType;
    private final List<Consumer<ArcaneRigApi>> registrationCalls = new ArrayList<>();

    public ArcaneRigPlugin(@Nonnull JavaPluginInit init) {
        super(init);
        instance = this;
        service = new ArcaneRigService();
    }

    @Override
    public void setup() {
        super.setup();

        arcaneRigDataComponentType = this.getEntityStoreRegistry().registerComponent(ArcaneRigData.class, ArcaneRigData.COMPONENT_ID, ArcaneRigData.CODEC);
        API = new ArcaneRigApiImpl(service);

        getEventRegistry().registerGlobal(PlayerReadyEvent.class, event -> {
            Player player = event.getPlayer();
            Ref<EntityStore> playerEntityRef = player.getReference();
            Store<EntityStore> store = playerEntityRef.getStore();


            var created = false;
            if (store.getComponent(playerEntityRef, ArcaneRigData.getComponentType()) == null) {
                store.ensureAndGetComponent(playerEntityRef, ArcaneRigData.getComponentType());
                created = true;
            }

            getLogger().atInfo().log((created ? "Created" : "Loaded") +" arcane rig data for player "+ player.getDisplayName());
        });

        getCodecRegistry(Interaction.CODEC).register("chibikookie_arcanerig_arcanering_interaction", RingInteraction.class, RingInteraction.CODEC);

        tryStartDevBootstrap();
    }

    @Override
    protected void start() {
        ArcaneRigApi api = API;
        registrationCalls.forEach(consumer -> {
            consumer.accept(api);
        });
        registrationCalls.clear();
    }

    @Override
    public void shutdown() {
        getLogger().atInfo().log("Plugin disabled!");
        instance = null;
    }

    private void tryStartDevBootstrap() {
        try {
            Class<?> c = Class.forName("com.chibikookie.arcanerig.dev.DevBootstrap");
            c.getMethod("install", ArcaneRigPlugin.class).invoke(null, this);
            getLogger().atInfo().log("[DEV] DevBootstrap installed");
        }
        catch (ClassNotFoundException ignored) {}
        catch (Throwable t) {
            getLogger().atWarning().log("[DEV] DevBootstrap failed: " + t);

        }
    }

    public static void onApiReady(Consumer<ArcaneRigApi> consumer) {
        ArcaneRigApi api = API;
        if (api == null) {
            instance.registrationCalls.add(consumer);
            return;
        }
        consumer.accept(api);
    }

    public static ArcaneRigApi api() {
        ArcaneRigApi api = API;
        if (api == null) {
            throw new IllegalStateException("Arcane Rig API is not ready yet");
        }
        return api;
    }

    public static ArcaneRigPlugin getInstance() {
        return instance;
    }

    @Nonnull
    public static ComponentType<EntityStore, ArcaneRigData> getArcaneRigDataComponentType() {
        return instance.arcaneRigDataComponentType;
    }

    private record ArcaneRigApiImpl(ArcaneRigService service) implements ArcaneRigApi {
        @Override
        public void registerSlot(SlotDescriptor slot) {
            service.registerSlot(slot);
        }

        @Override
        public List<SlotDescriptor> getRegisteredSlots() {
            return service.getSlots();
        }

        @Override
        public ItemStack getEquipped(@Nonnull Ref<EntityStore> ref, @Nonnull Store<EntityStore> store, String slotId) {
            ArcaneRigData data = store.ensureAndGetComponent(ref, ArcaneRigData.getComponentType());
            SlotEntry entry = data.getEntry(slotId);
            if (entry != null) {
                return entry.getStack();
            }
            return null;
        }

        @Override
        public boolean trySetEquipped(@Nonnull Ref<EntityStore> ref, @Nonnull Store<EntityStore> store, String slotId, @Nullable ItemStack stack) {
            ArcaneRigData data = store.ensureAndGetComponent(ref, ArcaneRigData.getComponentType());
            if (!service.canAddItemToSlot(slotId, stack)) {
                return false;
            }
            return data.putEntry(new SlotEntry(slotId, stack));
        }
    }
}
